import { IConfig } from "@app/shared/config";
import { PredefinedComponent, TileBehavior, TitleType } from "@app/shared/tile-menu";
import { Language } from "@app/shared/translation";
import { AppRoutes } from "src/app/modules/app/enums";

export const AppConfig: IConfig = {
        mainMenu : {
            tileConfig: [
                {   
                    targetURL: "",
                    imageURL: "pattern1.jpg",
                    iconURL: "settings",
                    text: "Ustawienia",
                    background: "#559334",
                    row: 1,
                    column: 1,
                    width: 1,
                    height: 2,
                    isVisible: true,
                    isActive: false,
                    behavior: TileBehavior.None,
                    component: PredefinedComponent.Settings,
                    titleType: TitleType.None,
                },
                {
                    targetURL: "",
                    imageURL: "pattern1.jpg",
                    iconURL: "thumb_up",
                    text: "Social Media",
                    background: "",
                    row: 1,
                    column: 2,
                    width: 3,
                    height: 1,
                    isVisible: true,
                    isActive: false,
                    behavior: TileBehavior.None,
                    component: PredefinedComponent.Socials,
                },
                {
                    targetURL: AppRoutes.OtherProjects,
                    imageURL: "pattern2.jpg",
                    iconURL: "precision_manufacturing",
                    text: "Doświadczenie",
                    background: "#ac6264",
                    row: 1,
                    column: 5,
                    width: 1,
                    height: 3,
                    isVisible: true,
                    isActive: true,
                    behavior: TileBehavior.Link,
                    titleType: TitleType.FullTile,
                },
                {
                    targetURL: AppRoutes.Projects,
                    imageURL: "",
                    iconURL: "architecture",
                    text: "Projekty",
                    background: "#772377",
                    row: 3,
                    column: 1,
                    width: 2,
                    height: 2,
                    isVisible: true,
                    isActive: true,
                    behavior: TileBehavior.Link,
                    titleType: TitleType.LeftSide,
                },
                {
                    targetURL: "",
                    imageURL: "pattern3.jpg",
                    iconURL: "beenhere",
                    text: "O stronie",
                    background: "",
                    row: 2,
                    column: 2,
                    width: 2,
                    height: 1,
                    isVisible: true,
                    isActive: true,
                    behavior: TileBehavior.Grow,
                    component: PredefinedComponent.About
                },
                {
                    targetURL: AppRoutes.AboutMe,
                    imageURL: "pattern1.jpg",
                    iconURL: "person",
                    text: "O mnie",
                    background: "#873456",
                    row: 2,
                    column: 4,
                    width: 1,
                    height: 2,
                    isVisible: true,
                    isActive: true,
                    behavior: TileBehavior.Link,
                    titleType: TitleType.BottomRibbon,
                },
                {
                    targetURL: "",
                    imageURL: "pattern1.jpg",
                    iconURL: "",
                    text: "",
                    background: "",
                    row: 3,
                    column: 3,
                    width: 1,
                    height: 2,
                    isVisible: true,
                    isActive: true,
                    behavior: TileBehavior.Fall,
                },
                {
                    targetURL: "",
                    imageURL: "pattern3.jpg",
                    iconURL: "alternate_email",
                    text: "Kontakt",
                    background: "",
                    row: 4,
                    column: 4,
                    width: 2,
                    height: 1,
                    isVisible: true,
                    isActive: true,
                    behavior: TileBehavior.TurnOver,
                    component: PredefinedComponent.Contact,
                    titleType: TitleType.RightSide
                }
            ]
        },
        defaultLanguage: Language.PL,
        personalData: {
            phoneNumber: "123456789",
            email: "email@gmail.com"
        }
    };