export enum ITSkill {
  ANGULAR = 'ANGULAR',
  JAVA = 'JAVA',
  TYPESCRIPT = 'TYPESCRIPT',
  JAVASCRIPT = 'JAVASCRIPT',
  REACT = 'REACT',
  CPP = 'CPP',
  CSHARP = 'CSHARP',
  PYTHON = 'PYTHON',
  GIT = 'GIT',
  JIRA = 'JIRA',
  HTML = 'HTML',
  CSS = 'CSS',
}
