name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Nx Cloud CI start (opcjonalne)
      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      # Install dependencies
      - run: npm install
      - run: npm ci --legacy-peer-deps

      - uses: nrwl/nx-set-shas@v4

      # Lint, test, build affected projects (opcjonalne)
      - run: npx nx affected -t lint test build
      - run: npx nx affected --parallel 1 -t e2e-ci

      # Build Angular app
      - name: Build Angular project
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/@portfolio/source
          clean: true
          publish_branch: gh-pages
